### ISSUE TITLE
Getting rid of gaug.es account

### ISSUE THREAD

**Issue by sckott** [ropensci/rgauges#18]
I'm giving up and falling back to google analytics. just not worth the cost given so few visits to my sites o_0

@karthik any interest in maintaining this?  Since I won't have an account any more to test against/use this pkg with.

**Comment by karthik** [comment]
Good question. I had the same thought myself ie dropping mine too. Should we consider paying for this for ropensci? Allowing us to add on as many other sites as we need?

**Comment by karthik** [comment]
For the package purposes alone it would be worth asking gauges if they might give you sandbox access.

**Comment by sckott** [comment]
just to have a record here - we talked in slack and seems like we're still on the fence about this...
